[

{ "data":"assetpath", "path":"/enablecdn/wordgirl/cdn_content/prettyprincess/game/" },

{ "data":"game", "stepsize":"230", "gamewidth":"40", "numwillowstocollect":"5"  },

{ "data":"location", "id":"1", "name":"village", "realname":"Village", "vocabwords":"whimsical,effervescent,fanciful", "similar":"forest,swamp", "different":"forest,swamp" },
{ "data":"location", "id":"2", "name":"swamp", "realname":"Swamp", "vocabwords":"gloomy,forbidding,dreary", "similar":"village,castle,flowerfield", "different":"village,castle,flowerfield" },
{ "data":"location", "id":"3", "name":"castle", "realname":"Castle", "vocabwords":"mystical,magical,enchanted", "similar":"forest,swamp", "different":"forest,swamp" },
{ "data":"location", "id":"4", "name":"forest", "realname":"Forest", "vocabwords":"haunted,ominous,sinister", "similar":"village,castle,flowerfield", "different":"village,castle,flowerfield" },
{ "data":"location", "id":"5", "name":"flowerfield", "realname":"Flower Field", "vocabwords":"serene,tranquil,peaceful", "similar":"forest,swamp", "different":"forest,swamp" },

{ "data":"item", "id":"191", "type":"P", "location":"village", "name":"platform1-low", "code":"_L_", "image":"gameelements/platforms/village_platform.png", "ypos":"-110", "plevel":"10", "scale":"1.0" },
{ "data":"item", "id":"192", "type":"P", "location":"village", "name":"platform1-mid", "code":"_M_", "image":"gameelements/platforms/village_platform.png", "ypos":"-210", "plevel":"10", "scale":"1.0" },
{ "data":"item", "id":"193", "type":"P", "location":"village", "name":"platform1-high", "code":"_H_", "image":"gameelements/platforms/village_platform.png", "ypos":"-310", "plevel":"10", "scale":"1.0" },

{ "data":"item", "id":"291", "type":"P", "location":"swamp", "name":"platform2-low", "code":"_L_", "image":"gameelements/platforms/swamp_platform.png", "ypos":"-110", "plevel":"10", "scale":"1.0" },
{ "data":"item", "id":"292", "type":"P", "location":"swamp", "name":"platform2-mid", "code":"_M_", "image":"gameelements/platforms/swamp_platform.png", "ypos":"-210", "plevel":"10", "scale":"1.0" },
{ "data":"item", "id":"293", "type":"P", "location":"swamp", "name":"platform2-high", "code":"_H_", "image":"gameelements/platforms/swamp_platform.png", "ypos":"-310", "plevel":"10", "scale":"1.0" },

{ "data":"item", "id":"391", "type":"P", "location":"castle", "name":"platform3-low", "code":"_L_", "image":"gameelements/platforms/castle_platform.png", "ypos":"-110", "plevel":"10", "scale":"1.0" },
{ "data":"item", "id":"392", "type":"P", "location":"castle", "name":"platform3-mid", "code":"_M_", "image":"gameelements/platforms/castle_platform.png", "ypos":"-210", "plevel":"10", "scale":"1.0" },
{ "data":"item", "id":"393", "type":"P", "location":"castle", "name":"platform3-high", "code":"_H_", "image":"gameelements/platforms/castle_platform.png", "ypos":"-310", "plevel":"10", "scale":"1.0" },

{ "data":"item", "id":"491", "type":"P", "location":"forest", "name":"platform4-low", "code":"_L_", "image":"gameelements/platforms/forest_platform.png", "ypos":"-110", "plevel":"10", "scale":"1.0" },
{ "data":"item", "id":"492", "type":"P", "location":"forest", "name":"platform4-mid", "code":"_M_", "image":"gameelements/platforms/forest_platform.png", "ypos":"-210", "plevel":"10", "scale":"1.0" },
{ "data":"item", "id":"493", "type":"P", "location":"forest", "name":"platform4-high", "code":"_H_", "image":"gameelements/platforms/forest_platform.png", "ypos":"-310", "plevel":"10", "scale":"1.0" },

{ "data":"item", "id":"591", "type":"P", "location":"flowerfield", "name":"platform5-low", "code":"_L_", "image":"gameelements/platforms/flowerfield_platform.png", "ypos":"-110", "plevel":"10", "scale":"1.0" },
{ "data":"item", "id":"592", "type":"P", "location":"flowerfield", "name":"platform5-mid", "code":"_M_", "image":"gameelements/platforms/flowerfield_platform.png", "ypos":"-210", "plevel":"10", "scale":"1.0" },
{ "data":"item", "id":"593", "type":"P", "location":"flowerfield", "name":"platform5-high", "code":"_H_", "image":"gameelements/platforms/flowerfield_platform.png", "ypos":"-310", "plevel":"10", "scale":"1.0" },

{ "data":"item", "id":"101", "type":"O", "location":"village", "code":"-A-", "name":"gnome", "image":"gameelements/obstacles/village/village_gnome.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"102", "type":"O", "location":"village", "code":"-B-", "name":"hat", "image":"gameelements/obstacles/village/village_hat.png", "ypos":"15", "scale":"0.75" },
{ "data":"item", "id":"103", "type":"O", "location":"village", "code":"-C-", "name":"sparklepony", "image":"gameelements/obstacles/village/village_sparklepony.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"104", "type":"O", "location":"village", "code":"-D-", "name":"tree", "image":"gameelements/obstacles/village/village_tree.png", "ypos":"15", "scale":"1.2" },
{ "data":"item", "id":"105", "type":"O", "location":"village", "code":"-E-", "name":"squirrel", "image":"gameelements/obstacles/village/village_squirrel.png", "ypos":"15", "scale":"0.85" },
{ "data":"item", "id":"106", "type":"O", "location":"village", "code":"-F-", "name":"barrel", "image":"gameelements/obstacles/village/village_barrel.png", "ypos":"15", "scale":"0.75" },
{ "data":"item", "id":"107", "type":"O", "location":"village", "code":"-G-", "name":"spinner", "image":"gameelements/obstacles/village/village_spinner.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"108", "type":"O", "location":"village", "code":"-H-", "name":"vase", "image":"gameelements/obstacles/village/village_vase.png", "ypos":"15", "scale":"0.8" },
{ "data":"item", "id":"109", "type":"O", "location":"village", "code":"-I-", "name":"haystack", "image":"gameelements/obstacles/village/village_haystack.png", "ypos":"15", "scale":"1.0" },

{ "data":"item", "id":"1101", "type":"R", "location":"village", "code":"-A-", "name":"riddle_gnome", "image":"gameelements/riddles/village/riddle_village_gnome.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1102", "type":"R", "location":"village", "code":"-B-", "name":"riddle_hat", "image":"gameelements/riddles/village/riddle_village_hat.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1103", "type":"R", "location":"village", "code":"-C-", "name":"riddle_sparklepony", "image":"gameelements/riddles/village/riddle_village_sparklepony.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1104", "type":"R", "location":"village", "code":"-D-", "name":"riddle_tree", "image":"gameelements/riddles/village/riddle_village_tree.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1105", "type":"R", "location":"village", "code":"-E-", "name":"riddle_squirrel", "image":"gameelements/riddles/village/riddle_village_squirrel.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1106", "type":"R", "location":"village", "code":"-F-", "name":"riddle_barrel", "image":"gameelements/riddles/village/riddle_village_barrel.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1107", "type":"R", "location":"village", "code":"-G-", "name":"riddle_spinner", "image":"gameelements/riddles/village/riddle_village_spinner.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1108", "type":"R", "location":"village", "code":"-H-", "name":"riddle_vase", "image":"gameelements/riddles/village/riddle_village_vase.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1109", "type":"R", "location":"village", "code":"-I-", "name":"riddle_haystack", "image":"gameelements/riddles/village/riddle_village_haystack.png", "ypos":"0", "scale":"1.0" },

{ "data":"item", "id":"201", "type":"O", "location":"swamp", "code":"-A-", "name":"trap", "image":"gameelements/obstacles/swamp/swamp_trap.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"202", "type":"O", "location":"swamp", "code":"-B-", "name":"rock", "image":"gameelements/obstacles/swamp/swamp_rock.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"203", "type":"O", "location":"swamp", "code":"-C-", "name":"dirtclump", "image":"gameelements/obstacles/swamp/swamp_dirtclump.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"204", "type":"O", "location":"swamp", "code":"-D-", "name":"tumbleweed", "image":"gameelements/obstacles/swamp/swamp_tumbleweed.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"205", "type":"O", "location":"swamp", "code":"-E-", "name":"bush", "image":"gameelements/obstacles/swamp/swamp_bush.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"206", "type":"O", "location":"swamp", "code":"-F-", "name":"fern", "image":"gameelements/obstacles/swamp/swamp_fern.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"207", "type":"O", "location":"swamp", "code":"-G-", "name":"alligator", "image":"gameelements/obstacles/swamp/swamp_alligator.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"208", "type":"O", "location":"swamp", "code":"-H-", "name":"burntwood", "image":"gameelements/obstacles/swamp/swamp_burntwood.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"209", "type":"O", "location":"swamp", "code":"-I-", "name":"hole", "image":"gameelements/obstacles/swamp/swamp_hole.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"210", "type":"O", "location":"swamp", "code":"-J-", "name":"owlfence", "image":"gameelements/obstacles/swamp/swamp_owlfence.png", "ypos":"35", "scale":"1.0" },
{ "data":"item", "id":"211", "type":"O", "location":"swamp", "code":"-K-", "name":"spookytree1", "image":"gameelements/obstacles/swamp/swamp_spookytree1.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"212", "type":"O", "location":"swamp", "code":"-L-", "name":"spookytree2", "image":"gameelements/obstacles/swamp/swamp_spookytree2.png", "ypos":"15", "scale":"1.0" },

{ "data":"item", "id":"1201", "type":"R", "location":"swamp", "code":"-A-", "name":"riddle_trap", "image":"gameelements/riddles/swamp/riddle_swamp_trap.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1202", "type":"R", "location":"swamp", "code":"-B-", "name":"riddle_rock", "image":"gameelements/riddles/swamp/riddle_swamp_rock.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1203", "type":"R", "location":"swamp", "code":"-C-", "name":"riddle_dirtclump", "image":"gameelements/riddles/swamp/riddle_swamp_dirtclump.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1204", "type":"R", "location":"swamp", "code":"-D-", "name":"riddle_tumbleweed", "image":"gameelements/riddles/swamp/riddle_swamp_tumbleweed.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1205", "type":"R", "location":"swamp", "code":"-E-", "name":"riddle_bush", "image":"gameelements/riddles/swamp/riddle_swamp_bush.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1206", "type":"R", "location":"swamp", "code":"-F-", "name":"riddle_fern", "image":"gameelements/riddles/swamp/riddle_swamp_fern.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1207", "type":"R", "location":"swamp", "code":"-G-", "name":"riddle_alligator", "image":"gameelements/riddles/swamp/riddle_swamp_alligator.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1208", "type":"R", "location":"swamp", "code":"-H-", "name":"riddle_burntwood", "image":"gameelements/riddles/swamp/riddle_swamp_burntwood.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1209", "type":"R", "location":"swamp", "code":"-I-", "name":"riddle_hole", "image":"gameelements/riddles/swamp/riddle_swamp_hole.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1210", "type":"R", "location":"swamp", "code":"-J-", "name":"riddle_owlfence", "image":"gameelements/riddles/swamp/riddle_swamp_owlfence.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1211", "type":"R", "location":"swamp", "code":"-K-", "name":"riddle_spookytree1", "image":"gameelements/riddles/swamp/riddle_swamp_spookytree1.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1212", "type":"R", "location":"swamp", "code":"-L-", "name":"riddle_spookytree2", "image":"gameelements/riddles/swamp/riddle_swamp_spookytree2.png", "ypos":"0", "scale":"1.0" },

{ "data":"item", "id":"301", "type":"O", "location":"castle", "code":"-A-", "name":"scepter", "image":"gameelements/obstacles/castle/castle_scepter.png", "ypos":"15", "scale":"0.75" },
{ "data":"item", "id":"302", "type":"O", "location":"castle", "code":"-B-", "name":"present", "image":"gameelements/obstacles/castle/castle_present.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"303", "type":"O", "location":"castle", "code":"-C-", "name":"wands", "image":"gameelements/obstacles/castle/castle_wands.png", "ypos":"15", "scale":"0.75" },
{ "data":"item", "id":"304", "type":"O", "location":"castle", "code":"-D-", "name":"jewels", "image":"gameelements/obstacles/castle/castle_jewels.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"305", "type":"O", "location":"castle", "code":"-E-", "name":"dragon1", "image":"gameelements/obstacles/castle/castle_dragon1.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"307", "type":"O", "location":"castle", "code":"-G-", "name":"dragon2", "image":"gameelements/obstacles/castle/castle_dragon2.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"308", "type":"O", "location":"castle", "code":"-H-", "name":"unicorn", "image":"gameelements/obstacles/castle/castle_unicorn.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"309", "type":"O", "location":"castle", "code":"-I-", "name":"statue", "image":"gameelements/obstacles/castle/castle_statue.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"310", "type":"O", "location":"castle", "code":"-J-", "name":"mirror", "image":"gameelements/obstacles/castle/castle_mirror.png", "ypos":"15", "scale":"0.75" },

{ "data":"item", "id":"1301", "type":"R", "location":"castle", "code":"-A-", "name":"riddle_scepter", "image":"gameelements/riddles/castle/riddle_castle_scepter.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1302", "type":"R", "location":"castle", "code":"-B-", "name":"riddle_present", "image":"gameelements/riddles/castle/riddle_castle_present.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1303", "type":"R", "location":"castle", "code":"-C-", "name":"riddle_wands", "image":"gameelements/riddles/castle/riddle_castle_wands.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1304", "type":"R", "location":"castle", "code":"-D-", "name":"riddle_jewels", "image":"gameelements/riddles/castle/riddle_castle_jewels.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1305", "type":"R", "location":"castle", "code":"-E-", "name":"riddle_dragon1", "image":"gameelements/riddles/castle/riddle_castle_dragon1.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1307", "type":"R", "location":"castle", "code":"-G-", "name":"riddle_dragon2", "image":"gameelements/riddles/castle/riddle_castle_dragon2.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1308", "type":"R", "location":"castle", "code":"-H-", "name":"riddle_unicorn", "image":"gameelements/riddles/castle/riddle_castle_unicorn.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1309", "type":"R", "location":"castle", "code":"-I-", "name":"riddle_statue", "image":"gameelements/riddles/castle/riddle_castle_statue.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1310", "type":"R", "location":"castle", "code":"-J-", "name":"riddle_mirror", "image":"gameelements/riddles/castle/riddle_castle_mirror.png", "ypos":"0", "scale":"1.0" },

{ "data":"item", "id":"401", "type":"O", "location":"forest", "code":"-A-", "name":"skull", "image":"gameelements/obstacles/forest/forest_skull.png", "ypos":"15", "scale":"0.7" },
{ "data":"item", "id":"402", "type":"O", "location":"forest", "code":"-B-", "name":"jackolantern", "image":"gameelements/obstacles/forest/forest_jackolantern.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"403", "type":"O", "location":"forest", "code":"-C-", "name":"ghosts", "image":"gameelements/obstacles/forest/forest_ghosts.png", "ypos":"20", "scale":"1.0" },
{ "data":"item", "id":"404", "type":"O", "location":"forest", "code":"-D-", "name":"tombstone1", "image":"gameelements/obstacles/forest/forest_tombstone1.png", "ypos":"30", "scale":"1.0" },
{ "data":"item", "id":"405", "type":"O", "location":"forest", "code":"-E-", "name":"spider", "image":"gameelements/obstacles/forest/forest_spider.png", "ypos":"-330", "scale":"1.0", "hanging":"yes" },
{ "data":"item", "id":"406", "type":"O", "location":"forest", "code":"-F-", "name":"tombstone2", "image":"gameelements/obstacles/forest/forest_tombstone2.png", "ypos":"30", "scale":"1.0" },
{ "data":"item", "id":"407", "type":"O", "location":"forest", "code":"-G-", "name":"gargoyle", "image":"gameelements/obstacles/forest/forest_gargoyle.png", "ypos":"25", "scale":"1.0" },

{ "data":"item", "id":"1401", "type":"R", "location":"forest", "code":"-A-", "name":"riddle_skull", "image":"gameelements/riddles/forest/riddle_forest_skull.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1402", "type":"R", "location":"forest", "code":"-B-", "name":"riddle_jackolantern", "image":"gameelements/riddles/forest/riddle_forest_jackolantern.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1403", "type":"R", "location":"forest", "code":"-C-", "name":"riddle_ghosts", "image":"gameelements/riddles/forest/riddle_forest_ghosts.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1404", "type":"R", "location":"forest", "code":"-D-", "name":"riddle_tombstone1", "image":"gameelements/riddles/forest/riddle_forest_tombstone1.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1405", "type":"R", "location":"forest", "code":"-E-", "name":"riddle_spider", "image":"gameelements/riddles/forest/riddle_forest_spider.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1406", "type":"R", "location":"forest", "code":"-F-", "name":"riddle_tombstone2", "image":"gameelements/riddles/forest/riddle_forest_tombstone2.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1407", "type":"R", "location":"forest", "code":"-G-", "name":"riddle_gargoyle", "image":"gameelements/riddles/forest/riddle_forest_gargoyle.png", "ypos":"0", "scale":"1.0" },

{ "data":"item", "id":"501", "type":"O", "location":"flowerfield", "code":"-A-", "name":"snail", "image":"gameelements/obstacles/field/flowerfield_snail.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"502", "type":"O", "location":"flowerfield", "code":"-B-", "name":"log", "image":"gameelements/obstacles/field/flowerfield_log.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"503", "type":"O", "location":"flowerfield", "code":"-C-", "name":"dirt", "image":"gameelements/obstacles/field/flowerfield_dirt.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"504", "type":"O", "location":"flowerfield", "code":"-D-", "name":"bush1", "image":"gameelements/obstacles/field/flowerfield_bush1.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"505", "type":"O", "location":"flowerfield", "code":"-E-", "name":"shrub", "image":"gameelements/obstacles/field/flowerfield_shrub.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"506", "type":"O", "location":"flowerfield", "code":"-F-", "name":"flowers", "image":"gameelements/obstacles/field/flowerfield_flowers.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"507", "type":"O", "location":"flowerfield", "code":"-G-", "name":"bonsaitree", "image":"gameelements/obstacles/field/flowerfield_bonsaitree.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"508", "type":"O", "location":"flowerfield", "code":"-H-", "name":"bush2", "image":"gameelements/obstacles/field/flowerfield_bush2.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"509", "type":"O", "location":"flowerfield", "code":"-I-", "name":"birdbath", "image":"gameelements/obstacles/field/flowerfield_birdbath.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"510", "type":"O", "location":"flowerfield", "code":"-J-", "name":"pottedplant", "image":"gameelements/obstacles/field/flowerfield_pottedplant.png", "ypos":"15", "scale":"1.0" },
{ "data":"item", "id":"511", "type":"O", "location":"flowerfield", "code":"-K-", "name":"giraffe", "image":"gameelements/obstacles/field/flowerfield_giraffe.png", "ypos":"15", "scale":"1.0" },

{ "data":"item", "id":"1501", "type":"R", "location":"flowerfield", "code":"-A-", "name":"riddle_snail", "image":"gameelements/riddles/field/riddle_flowerfield_snail.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1502", "type":"R", "location":"flowerfield", "code":"-B-", "name":"riddle_log", "image":"gameelements/riddles/field/riddle_flowerfield_log.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1503", "type":"R", "location":"flowerfield", "code":"-C-", "name":"riddle_dirt", "image":"gameelements/riddles/field/riddle_flowerfield_dirt.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1504", "type":"R", "location":"flowerfield", "code":"-D-", "name":"riddle_bush1", "image":"gameelements/riddles/field/riddle_flowerfield_bush1.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1505", "type":"R", "location":"flowerfield", "code":"-E-", "name":"riddle_shrub", "image":"gameelements/riddles/field/riddle_flowerfield_shrub.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1506", "type":"R", "location":"flowerfield", "code":"-F-", "name":"riddle_flowers", "image":"gameelements/riddles/field/riddle_flowerfield_flowers.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1507", "type":"R", "location":"flowerfield", "code":"-G-", "name":"riddle_bonsaitree", "image":"gameelements/riddles/field/riddle_flowerfield_bonsaitree.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1508", "type":"R", "location":"flowerfield", "code":"-H-", "name":"riddle_bush2", "image":"gameelements/riddles/field/riddle_flowerfield_bush2.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1509", "type":"R", "location":"flowerfield", "code":"-I-", "name":"riddle_birdbath", "image":"gameelements/riddles/field/riddle_flowerfield_birdbath.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1510", "type":"R", "location":"flowerfield", "code":"-J-", "name":"riddle_pottedplant", "image":"gameelements/riddles/field/riddle_flowerfield_pottedplant.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"1511", "type":"R", "location":"flowerfield", "code":"-K-", "name":"riddle_giraffe", "image":"gameelements/riddles/field/riddle_flowerfield_giraffe.png", "ypos":"0", "scale":"1.0" },


{ "data":"item", "id":"811", "type":"W", "location":"village", "name":"willow1-low", "code":"+L+", "image":"gameelements/willows/placeholder.png", "ypos":"0", "scale":"0.85" },
{ "data":"item", "id":"812", "type":"W", "location":"village", "name":"willow1-med", "code":"+M+", "image":"gameelements/willows/placeholder.png", "ypos":"-140", "scale":"0.85" },
{ "data":"item", "id":"813", "type":"W", "location":"village", "name":"willow1-high", "code":"+H+", "image":"gameelements/willows/placeholder.png", "ypos":"-230", "scale":"0.85" },
{ "data":"item", "id":"821", "type":"W", "location":"swamp", "name":"willow2-low", "code":"+L+", "image":"gameelements/willows/placeholder.png", "ypos":"0", "scale":"0.85" },
{ "data":"item", "id":"822", "type":"W", "location":"swamp", "name":"willow2-med", "code":"+M+", "image":"gameelements/willows/placeholder.png", "ypos":"-140", "scale":"0.85" },
{ "data":"item", "id":"823", "type":"W", "location":"swamp", "name":"willow2-high", "code":"+H+", "image":"gameelements/willows/placeholder.png", "ypos":"-230", "scale":"0.85" },
{ "data":"item", "id":"831", "type":"W", "location":"castle", "name":"willow3-low", "code":"+L+", "image":"gameelements/willows/placeholder.png", "ypos":"0", "scale":"0.85" },
{ "data":"item", "id":"832", "type":"W", "location":"castle", "name":"willow3-med", "code":"+M+", "image":"gameelements/willows/placeholder.png", "ypos":"-140", "scale":"0.85" },
{ "data":"item", "id":"833", "type":"W", "location":"castle", "name":"willow3-high", "code":"+H+", "image":"gameelements/willows/placeholder.png", "ypos":"-230", "scale":"0.85" },
{ "data":"item", "id":"841", "type":"W", "location":"forest", "name":"willow4-low", "code":"+L+", "image":"gameelements/willows/placeholder.png", "ypos":"0", "scale":"0.85" },
{ "data":"item", "id":"842", "type":"W", "location":"forest", "name":"willow4-med", "code":"+M+", "image":"gameelements/willows/placeholder.png", "ypos":"-140", "scale":"0.85" },
{ "data":"item", "id":"843", "type":"W", "location":"forest", "name":"willow4-high", "code":"+H+", "image":"gameelements/willows/placeholder.png", "ypos":"-230", "scale":"0.85" },
{ "data":"item", "id":"851", "type":"W", "location":"flowerfield", "name":"willow5-low", "code":"+L+", "image":"gameelements/willows/placeholder.png", "ypos":"0", "scale":"0.85" },
{ "data":"item", "id":"852", "type":"W", "location":"flowerfield", "name":"willow5-med", "code":"+M+", "image":"gameelements/willows/placeholder.png", "ypos":"-140", "scale":"0.85" },
{ "data":"item", "id":"853", "type":"W", "location":"flowerfield", "name":"willow5-high", "code":"+H+", "image":"gameelements/willows/placeholder.png", "ypos":"-230", "scale":"0.85" },

{ "data":"item", "id":"901", "type":"C", "location":"", "code":"-Z-", "name":"checkpoint", "image":"gameelements/checkpoints/checkpoint.png", "ypos":"0", "scale":"1.0" },
{ "data":"item", "id":"902", "type":"C", "location":"", "code":"-X-", "name":"barrier", "image":"gameelements/checkpoints/pp_starttower.png", "ypos":"40", "scale":"1.0" },
{ "data":"item", "id":"903", "type":"C", "location":"", "code":"-Y-", "name":"tower", "image":"gameelements/checkpoints/pp_endtower.png", "ypos":"40", "scale":"1.0" },

{ "data":"willows",     "location":"village", "set":"1",  "map":"+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++" },
{ "data":"platforms",   "location":"village", "set":"1",  "map":"___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,_L_,___,___,___,___,___,_L_,_M_,___,___,___,___,___,___,___,___,___,___,_L_,___,_M_,___,___,___,___,___,___,___,___,___,___,___,___,_L_,___,_M_,___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,_M_,_L_,___,___,___,_L_,___,_M_,___,___,___,_L_,___,_M_,___,___,___,___,___,___,___" },
{ "data":"obstacles",   "location":"village", "set":"1",  "map":"---,---,---,---,---,---,---,---,---,---,---,-A-,---,-B-,---,-C-,---,---,-F-,---,---,---,-H-,---,-E-,-D-,---,---,-I-,---,---,-I-,---,---,-A-,---,---,---,-F-,---,---,-C-,---,-G-,---,-C-,---,-E-,---,-I-,---,-I-,---,-D-,---,---,-F-,---,-H-,---,-H-,---,-I-,---,-B-,---,-C-,---,---,---,---,-G-,---,---,-E-,---,-D-,---,---,---,-H-,---,-F-,---,-H-,---,---,---,---" },
{ "data":"checkpoints", "location":"village", "set":"1",  "map":"-X-,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,-Z-,-Y-" },

{ "data":"willows",     "location":"village", "set":"2",  "map":"+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++" },
{ "data":"platforms",   "location":"village", "set":"2",  "map":"___,___,___,___,___,___,___,___,___,___,___,_L_,_M_,___,_L_,___,___,___,___,___,_L_,___,___,___,_L_,___,_M_,___,_L_,___,___,___,___,_L_,___,___,_L_,___,___,___,___,_L_,_M_,_H_,_M_,___,_L_,___,___,___,___,___,_L_,___,_L_,___,_M_,___,___,_L_,_M_,___,_M_,_L_,___,___,___,___,___,___,___,_L_,___,___,___,___,___,___,___,_L_,___,___,___,___,___,___,___,___,___" },
{ "data":"obstacles",   "location":"village", "set":"2",  "map":"---,---,---,---,---,---,---,---,---,-F-,---,---,---,-D-,---,---,---,-C-,---,-E-,---,-G-,---,---,---,-A-,---,-B-,---,---,---,---,-H-,---,-F-,---,---,-E-,---,-I-,---,---,---,-G-,---,-F-,---,-B-,---,-C-,---,-E-,---,-G-,---,-A-,---,-D-,---,---,---,-I-,---,---,-A-,---,-E-,---,-B-,---,-F-,---,-G-,---,---,-A-,---,-C-,---,---,-H-,---,-I-,---,---,---,---,---,---" },
{ "data":"checkpoints", "location":"village", "set":"2",  "map":"-X-,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,-Z-,-Y-" },

{ "data":"willows",     "location":"village", "set":"3",  "map":"+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++" },
{ "data":"platforms",   "location":"village", "set":"3",  "map":"___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,_L_,___,___,_L_,___,___,___,___,___,___,_L_,___,___,_L_,_M_,___,_L_,___,_M_,___,___,___,_L_,___,_M_,___,_L_,___,_L_,_M_,___,_L_,___,___,_L_,_M_,___,_M_,___,_M_,_L_,___,___,___,___,___,_L_,___,_L_,_M_,_M_,___,___,___,___,___,___,___,_L_,___,_M_,___,_L_,___,___,___,___,___,___,___,___,___" },
{ "data":"obstacles",   "location":"village", "set":"3",  "map":"---,---,---,---,---,---,---,---,---,-A-,---,-E-,---,-A-,---,-B-,---,---,---,-I-,---,---,-C-,---,-F-,---,-F-,---,---,-E-,---,---,-D-,---,-E-,---,-D-,---,-G-,---,-C-,---,-A-,---,-B-,---,---,-H-,---,-H-,---,---,-E-,-D-,---,-D-,---,---,-I-,---,-A-,---,-F-,---,---,---,-C-,---,-C-,---,-H-,---,-E-,---,-I-,---,-G-,---,-I-,---,---,-E-,---,-A-,---,---,---,---,---" },
{ "data":"checkpoints", "location":"village", "set":"3",  "map":"-X-,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,-Z-,-Y-" },


{ "data":"willows",     "location":"swamp", "set":"1",  "map":"+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+L+,+++,+++" },
{ "data":"platforms",   "location":"swamp", "set":"1",  "map":"___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,_L_,___,___,_L_,___,___,___,_L_,___,_M_,_L_,___,_L_,___,_L_,___,_L_,___,_M_,_L_,___,_M_,___,_M_,___,_L_,___,___,___,___,___,_L_,_M_,___,_M_,_L_,___,___,___,___,_L_,___,_M_,___,_L_,___,_M_,___,_M_,___,_M_,___,_L_,___,___,___,___,___,___,_L_,___,_M_,___,_L_,___,_M_,_M_,___,___,___,___,_M_,___,___" },
{ "data":"obstacles",   "location":"swamp", "set":"1",  "map":"---,---,---,---,---,---,---,---,---,-A-,---,-C-,---,---,-F-,---,---,-D-,---,-G-,---,-J-,---,---,-E-,---,-B-,---,-I-,---,---,---,-H-,---,---,-A-,---,-L-,---,-G-,---,-F-,---,-B-,---,-D-,---,-H-,-K-,---,---,-E-,---,-G-,---,---,-A-,---,-D-,---,---,-E-,---,-I-,---,-B-,---,---,-A-,---,-C-,---,-D-,---,---,-J-,---,-B-,---,-A-,-F-,---,-K-,---,---,---,---,---,---" },
{ "data":"checkpoints", "location":"swamp", "set":"1",  "map":"-X-,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,-Z-,-Y-" },

{ "data":"willows",     "location":"swamp", "set":"2",  "map":"+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+L+,+++,+++,+++,+L+,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++" },
{ "data":"platforms",   "location":"swamp", "set":"2",  "map":"___,___,___,___,___,___,___,___,___,___,___,___,___,_L_,___,___,___,___,_L_,___,_M_,___,_L_,_M_,___,___,_L_,___,_L_,_M_,___,_M_,_L_,___,_L_,___,_M_,___,_L_,___,___,___,___,___,___,_L_,___,_M_,___,_M_,_L_,___,_L_,___,___,___,___,___,___,_L_,___,_M_,___,_L_,___,_L_,___,_L_,___,_M_,_L_,___,___,_L_,___,___,_L_,___,_M_,___,_L_,___,___,___,___,___,___,___,___" },
{ "data":"obstacles",   "location":"swamp", "set":"2",  "map":"---,---,---,---,---,---,---,---,---,-A-,---,-F-,---,---,-D-,---,-C-,---,---,-E-,---,-I-,---,---,-K-,---,---,-A-,---,---,-L-,-J-,---,-B-,---,-B-,-C-,---,---,-F-,---,-G-,---,-E-,---,---,-C-,-A-,-K-,-A-,---,---,-I-,---,-D-,---,-G-,---,-F-,---,-B-,---,-G-,---,-B-,---,-E-,---,-H-,-J-,---,-D-,---,-I-,---,-C-,---,-E-,---,-G-,---,-B-,---,-A-,---,---,---,---,---" },
{ "data":"checkpoints", "location":"swamp", "set":"2",  "map":"-X-,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,-Z-,-Y-" },

{ "data":"willows",     "location":"swamp", "set":"3",  "map":"+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+M+,+++,+++,+L+,+++,+++,+++,+++,+++,+L+,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++" },
{ "data":"platforms",   "location":"swamp", "set":"3",  "map":"___,___,___,___,___,___,___,___,___,___,___,___,___,_L_,___,_M_,___,_L_,___,_M_,___,_L_,___,___,_L_,___,_M_,_H_,_M_,_L_,___,___,_L_,___,_M_,___,_L_,___,___,___,___,___,_L_,___,___,___,_L_,_M_,___,_M_,_L_,___,___,_L_,___,_L_,___,___,___,___,___,___,___,_L_,___,___,_L_,_M_,___,_M_,___,_M_,_L_,___,_L_,___,_M_,___,_L_,___,___,_L_,___,___,___,___,___,___,___" },
{ "data":"obstacles",   "location":"swamp", "set":"3",  "map":"---,---,---,---,---,---,---,---,---,-A-,---,-C-,---,---,-D-,---,-E-,---,-B-,---,-G-,---,-F-,---,---,-I-,---,-G-,---,---,-C-,-F-,---,-A-,---,-A-,---,-D-,---,-B-,---,-H-,---,-G-,---,-E-,---,---,-L-,---,---,-J-,---,-I-,-B-,-I-,---,-C-,---,-D-,---,-H-,---,-I-,---,-F-,---,---,-K-,---,-L-,---,---,-A-,---,-D-,---,-D-,---,-G-,---,---,-J-,---,---,---,---,---,---" },
{ "data":"checkpoints", "location":"swamp", "set":"3",  "map":"-X-,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,-Z-,-Y-" },


{ "data":"willows",     "location":"castle", "set":"1",  "map":"+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+L+,+++,+++,+H+,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+L+,+++,+++" },
{ "data":"platforms",   "location":"castle", "set":"1",  "map":"___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,_L_,_M_,___,___,_L_,___,___,_L_,_M_,___,_L_,___,___,___,___,_L_,_M_,___,_L_,___,___,___,_L_,___,_M_,___,_L_,___,___,___,___,___,___,___,___,_L_,_M_,___,_L_,___,___,___,___,_L_,___,_M_,___,_M_,___,_M_,_L_,___,___,___,_L_,_M_,_L_,___,___,___,___,___,_L_,___,_L_,___,___,___,___,___,___,___,___" },
{ "data":"obstacles",   "location":"castle", "set":"1",  "map":"---,---,---,---,---,---,---,---,---,-A-,---,-D-,---,-B-,---,-D-,---,-D-,---,-C-,---,-H-,---,---,---,-H-,---,-D-,---,---,-B-,---,-E-,-G-,---,---,-B-,---,---,-C-,---,-I-,---,-A-,---,-E-,---,-D-,---,-C-,---,---,---,-G-,---,-A-,---,-B-,---,---,-H-,---,-G-,---,-I-,---,---,-D-,---,-C-,---,-D-,---,-D-,---,-E-,---,-A-,---,-H-,---,---,-B-,---,-B-,---,---,---,---" },
{ "data":"checkpoints", "location":"castle", "set":"1",  "map":"-X-,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,-Z-,-Y-" },

{ "data":"willows",     "location":"castle", "set":"2",  "map":"+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++" },
{ "data":"platforms",   "location":"castle", "set":"2",  "map":"___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,_L_,___,___,___,___,_L_,___,_L_,___,___,___,___,_L_,_M_,___,_M_,_L_,___,___,___,_L_,___,___,_L_,___,___,___,___,___,_L_,___,_L_,___,_M_,___,_M_,_L_,___,___,___,___,_L_,___,_L_,___,___,___,_L_,___,_M_,___,_L_,___,_L_,___,_L_,___,___,___,___,___,___,_L_,___,_M_,_H_,_M_,_L_,___,___,___,___,___" },
{ "data":"obstacles",   "location":"castle", "set":"2",  "map":"---,---,---,---,---,---,---,---,---,-C-,---,-E-,---,-D-,---,-B-,---,-D-,---,-B-,---,---,-H-,---,-A-,---,-A-,---,---,-C-,---,-C-,---,-I-,---,-D-,---,-B-,---,---,-E-,---,-C-,---,-A-,---,-D-,---,-J-,---,-G-,---,---,-B-,---,-J-,---,---,-H-,---,-A-,---,-B-,---,-C-,---,-D-,---,-D-,---,-I-,---,-E-,---,-B-,---,---,-J-,---,-D-,---,-H-,---,---,---,---,---,---,---" },
{ "data":"checkpoints", "location":"castle", "set":"2",  "map":"-X-,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,-Z-,-Y-" },

{ "data":"willows",     "location":"castle", "set":"3",  "map":"+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+L+,+++,+++,+H+,+++,+++,+++,+++,+L+,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+L+,+++,+++" },
{ "data":"platforms",   "location":"castle", "set":"3",  "map":"___,___,___,___,___,___,___,___,___,___,___,___,___,_L_,___,_L_,___,_M_,_L_,___,___,_L_,___,_L_,___,_M_,___,_L_,_M_,_H_,_M_,_L_,___,___,___,_L_,_M_,___,_M_,___,_M_,_L_,_M_,___,_M_,___,_L_,___,___,___,___,_M_,_L_,_M_,___,___,___,_L_,_M_,___,_L_,_M_,_L_,_M_,___,___,___,_L_,___,_M_,___,_L_,_M_,___,_M_,_L_,___,_L_,___,___,___,___,___,___,___,___,___,___,___" },
{ "data":"obstacles",   "location":"castle", "set":"3",  "map":"---,---,---,---,---,---,---,---,---,-B-,---,-A-,---,---,-H-,---,-E-,-D-,---,---,-C-,---,-D-,---,-C-,---,-B-,---,-A-,-G-,-A-,---,-D-,---,-D-,---,-E-,---,---,-H-,---,---,-A-,---,---,-I-,---,-D-,---,-B-,---,-A-,---,-C-,---,-J-,---,---,-E-,---,---,-E-,---,---,-I-,---,-D-,---,-C-,---,-B-,---,-D-,---,-A-,---,-G-,---,-B-,---,-E-,---,-J-,---,---,---,---,---,---" },
{ "data":"checkpoints", "location":"castle", "set":"3",  "map":"-X-,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,-Z-,-Y-" },


{ "data":"willows",     "location":"forest", "set":"1",  "map":"+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++" },
{ "data":"platforms",   "location":"forest", "set":"1",  "map":"___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,_L_,___,___,___,___,___,_L_,___,_L_,___,___,_L_,___,_L_,___,_L_,___,___,___,___,_L_,___,_M_,___,_L_,___,___,_L_,___,___,___,___,___,___,___,___,_L_,___,_M_,___,_L_,___,_L_,___,_M_,___,_L_,___,___,___,___,___,_L_,___,___,_L_,___,___,_L_,___,_L_,___,_M_,___,_L_,___,___,___,___,___,___,___" },
{ "data":"obstacles",   "location":"forest", "set":"1",  "map":"---,---,---,---,---,---,---,---,---,-C-,---,-D-,---,-A-,---,---,-E-,---,-F-,---,-C-,---,-A-,---,-G-,---,---,-D-,---,-B-,---,-A-,---,---,-F-,---,-E-,---,-G-,-D-,-B-,---,-D-,---,---,-C-,---,-A-,---,-D-,---,-G-,---,---,-F-,---,-B-,---,-E-,---,-D-,---,-A-,---,-D-,---,-C-,---,-E-,---,-F-,---,---,-B-,---,---,-C-,---,---,---,-G-,---,-A-,---,---,---,---,---,---" },
{ "data":"checkpoints", "location":"forest", "set":"1",  "map":"-X-,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,-Z-,-Y-" },

{ "data":"willows",     "location":"forest", "set":"2",  "map":"+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++" },
{ "data":"platforms",   "location":"forest", "set":"2",  "map":"___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,_L_,___,___,___,_L_,___,_M_,___,_L_,___,___,___,___,_L_,___,_M_,___,___,_L_,___,___,_M_,___,___,___,___,_L_,___,_M_,___,_M_,___,_M_,___,_L_,___,___,___,_L_,___,_M_,___,_L_,___,___,___,_L_,___,_M_,___,_L_,___,___,_L_,___,___,_L_,_M_,_L_,___,___,___,___,___,___,___,___,___,___,___,___,___" },
{ "data":"obstacles",   "location":"forest", "set":"2",  "map":"---,---,---,---,---,---,---,---,---,-A-,---,-E-,---,-F-,---,-C-,---,---,-A-,---,-D-,---,-G-,---,-G-,---,-B-,---,-A-,---,---,-C-,---,-D-,---,---,-F-,---,-G-,---,-E-,---,-B-,---,-A-,---,-B-,---,-F-,---,-D-,---,-A-,---,-E-,---,-C-,---,-G-,---,-B-,---,-E-,---,-A-,---,-G-,---,-C-,---,---,-F-,---,---,-B-,---,-D-,---,-B-,---,-G-,---,-C-,---,---,---,---,---,---" },
{ "data":"checkpoints", "location":"forest", "set":"2",  "map":"-X-,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,-Z-,-Y-" },

{ "data":"willows",     "location":"forest", "set":"3",  "map":"+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+L+,+++,+++" },
{ "data":"platforms",   "location":"forest", "set":"3",  "map":"___,___,___,___,___,___,___,___,___,___,___,___,___,___,_L_,___,___,_L_,___,___,_L_,___,_M_,___,_L_,___,_L_,___,___,___,___,___,_L_,___,_M_,___,_L_,___,___,___,_L_,___,___,_L_,___,___,_L_,_M_,___,___,___,___,___,___,_L_,___,_M_,___,_L_,___,_L_,_M_,___,___,___,_L_,___,_M_,___,_L_,___,___,___,___,___,___,___,___,___,___,___,___,_L_,_M_,___,___,___,___,___" },
{ "data":"obstacles",   "location":"forest", "set":"3",  "map":"---,---,---,---,---,---,---,---,---,-B-,---,-A-,---,-A-,---,-C-,---,---,-E-,---,---,-D-,-F-,-D-,---,-F-,---,-E-,---,-G-,---,-C-,---,-B-,-A-,-B-,---,-C-,---,-E-,---,-A-,---,---,---,-D-,---,---,-B-,---,-C-,---,-D-,---,---,-G-,-A-,-D-,---,-G-,---,---,-B-,---,-E-,---,-A-,---,-A-,---,-E-,---,-B-,---,-C-,---,-F-,---,-C-,---,-D-,---,---,-G-,---,---,---,---,---" },
{ "data":"checkpoints", "location":"forest", "set":"3",  "map":"-X-,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,-Z-,-Y-" },


{ "data":"willows",     "location":"flowerfield", "set":"1",  "map":"+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+L+,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+L+,+++,+++" },
{ "data":"platforms",   "location":"flowerfield", "set":"1",  "map":"___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,_L_,_M_,___,_L_,___,___,___,___,___,_L_,___,_L_,___,_L_,___,___,_L_,_M_,___,_M_,_L_,___,___,___,___,___,___,___,_L_,_M_,_M_,_M_,_L_,___,_L_,___,_L_,_M_,_H_,_M_,_L_,___,_M_,___,___,___,___,___,_L_,___,_L_,___,_L_,_M_,___,_M_,_L_,___,_M_,_L_,___,___,___,___,_L_,_M_,___,_M_,_L_,___,___,___,___,___" },
{ "data":"obstacles",   "location":"flowerfield", "set":"1",  "map":"---,---,---,---,---,---,---,---,-A-,---,-C-,---,-D-,---,---,---,-E-,---,---,-I-,---,-H-,---,-F-,---,-J-,---,-B-,---,-G-,---,---,---,-K-,---,---,-A-,---,-C-,---,-H-,---,-B-,---,-F-,---,-F-,---,-G-,---,-A-,---,-C-,-J-,-E-,---,-B-,---,-K-,---,-B-,---,-D-,---,-C-,---,-H-,---,-E-,---,---,---,-J-,---,---,-B-,---,-A-,---,---,---,-I-,---,---,---,---,---,---,---" },
{ "data":"checkpoints", "location":"flowerfield", "set":"1",  "map":"-X-,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,-Z-,-Y-" },

{ "data":"willows",     "location":"flowerfield", "set":"2",  "map":"+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+L+,+++,+++" },
{ "data":"platforms",   "location":"flowerfield", "set":"2",  "map":"___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,_L_,___,_L_,___,_L_,___,_L_,_L_,___,_M_,_L_,___,___,___,___,_L_,___,_L_,___,___,___,___,___,___,_L_,___,_M_,___,_L_,___,___,___,___,___,_L_,_M_,___,_H_,_M_,_L_,___,___,_L_,___,_M_,___,_L_,___,_L_,___,___,___,___,___,___,___,___,___,___,___,___,_L_,_M_,___,_M_,_L_,___,___,___,___,___,___,___" },
{ "data":"obstacles",   "location":"flowerfield", "set":"2",  "map":"---,---,---,---,---,---,---,---,-B-,---,-B-,---,-A-,---,-A-,---,---,-G-,---,-J-,---,-G-,---,---,---,-F-,---,-E-,---,-D-,---,---,-K-,---,-C-,---,-H-,---,-C-,---,---,-B-,-G-,-A-,---,-A-,---,-E-,---,-C-,---,---,-K-,---,-D-,---,-J-,---,---,-E-,-G-,-E-,---,-D-,---,-A-,---,-B-,---,-F-,---,-B-,---,-H-,---,-H-,---,---,-C-,-J-,---,---,-A-,---,---,---,---,---,---" },
{ "data":"checkpoints", "location":"flowerfield", "set":"2",  "map":"-X-,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,-Z-,-Y-" },

{ "data":"willows",     "location":"flowerfield", "set":"3",  "map":"+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+M+,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+L+,+++,+++,+H+,+++,+++,+++,+++,+L+,+++,+++,+++,+++,+++,+H+,+++,+++,+++,+++,+++,+++,+L+,+++,+++" },
{ "data":"platforms",   "location":"flowerfield", "set":"3",  "map":"___,___,___,___,___,___,___,___,___,___,___,___,___,___,___,_L_,___,_M_,___,_L_,___,_M_,___,_L_,___,___,___,___,___,___,___,_L_,___,_L_,___,_L_,___,_L_,___,_M_,___,_H_,___,_M_,___,_L_,___,___,___,___,___,___,___,___,___,_L_,_M_,___,_M_,___,_L_,_M_,___,_M_,_L_,___,___,_L_,_M_,_L_,___,___,___,___,___,___,_L_,_M_,___,_M_,___,___,___,___,___,___,___,___,___" },
{ "data":"obstacles",   "location":"flowerfield", "set":"3",  "map":"---,---,---,---,---,---,---,---,-C-,---,-D-,---,-B-,---,-B-,---,-G-,---,-H-,---,-J-,---,-J-,---,---,-F-,---,-C-,---,-F-,---,---,-E-,---,-D-,---,-B-,---,-G-,-C-,---,---,-K-,---,-I-,---,-A-,---,-D-,---,-B-,---,-H-,---,-A-,---,-F-,-J-,-F-,---,---,-E-,-K-,-E-,---,---,-B-,---,-A-,---,-I-,---,-D-,---,-C-,---,---,-G-,-F-,---,---,-E-,---,---,---,---,---,---,---" },
{ "data":"checkpoints", "location":"flowerfield", "set":"3",  "map":"-X-,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---,-Z-,-Y-" },

{ "data":"riddle", "location":"village", "name":"village", "questions":"What shines and sparkles and belongs in a whimsical village?,What glistens and shimmers and belongs in an effervescent village?,What twinkles and glitters and belongs in a fanciful village?", "qvo":"lp_riddle_whimsicalvillage,lp_riddle_effervescentvillage,lp_riddle_fancifulvillage", "words":"whimsical,effervescent,fanciful", "props":"riddle_hat,riddle_sparklepony,riddle_vase", "similar":"forest,swamp", "different":"forest,swamp" },
{ "data":"riddle", "location":"swamp", "name":"swamp", "questions":"What's dark and murky and belongs in a gloomy swamp?,What's dismal and grim and belongs in a forbidding swamp?,What's bleak and dark and belongs in a dreary swamp?", "qvo":"lp_riddle_gloomyswamp,lp_riddle_forbiddingswamp,lp_riddle_drearyswamp", "words":"gloomy,forbidding,dreary", "props":"riddle_alligator,riddle_trap,riddle_owlfence,riddle_burntwood", "similar":"village,castle,flowerfield", "different":"village,castle,flowerfield" },
{ "data":"riddle", "location":"castle", "name":"castle", "questions":"What's amazing and astounding and belongs in a mystical castle?,What's thrilling and enchanting and belongs in a magical castle?,What's charming and delightful and belongs in an enchanted castle?", "qvo":"lp_riddle_mysticalcastle,lp_riddle_magicalcastle,lp_riddle_enchantedcastle", "words":"mystical,magical,enchanted", "props":"riddle_dragon1,riddle_unicorn,riddle_jewels,riddle_mirror,riddle_wands", "similar":"forest,swamp", "different":"forest,swamp" },
{ "data":"riddle", "location":"forest", "name":"forest", "questions":"What's spooky and scary and belongs in a haunted forest?,What's creepy and scary and belongs in an ominous forest?,What's spooky and frightening and belongs in a sinister forest?", "qvo":"lp_riddle_hauntedforest,lp_riddle_ominousforest,lp_riddle_sinisterforest", "words":"haunted,ominous,sinister", "props":"riddle_tombstone1,riddle_skull,riddle_jackolantern,riddle_spider,riddle_ghosts,riddle_gargoyle", "similar":"village,castle,flowerfield", "different":"village,castle,flowerfield" },
{ "data":"riddle", "location":"flowerfield", "name":"flowerfield", "questions":"What's quiet and calm and belongs in a serene field of flowers?,What's soft and gentle and belongs in a tranquil field of flowers?,What's tranquil and still and belongs in a peaceful field of flowers?", "qvo":"lp_riddle_sereneflowerfield,lp_riddle_tranquilflowerfield,lp_riddle_peacefulflowerfield", "words":"serene,tranquil,peaceful", "props":"riddle_flowers,riddle_pottedplant,riddle_birdbath,riddle_bonsaitree", "similar":"forest,swamp", "different":"forest,swamp" },

{ "data":"bossbattle", "location":"village", "vocabwords":"whimsical,effervescent,fanciful", "willow":"811" },
{ "data":"bossbattle", "location":"swamp", "vocabwords":"gloomy,forbidding,dreary", "willow":"821" },
{ "data":"bossbattle", "location":"castle", "vocabwords":"mystical,magical,enchanted", "willow":"831" },
{ "data":"bossbattle", "location":"forest", "vocabwords":"haunted,ominous,sinister", "willow":"841" },
{ "data":"bossbattle", "location":"flowerfield", "vocabwords":"serene,tranquil,peaceful", "willow":"851" },

{ "data":"bosswords", "word":"whimsical", "distractors":"cumbersome,eerie,unusual" },
{ "data":"bosswords", "word":"effervescent", "distractors":"harsh,gloomy,mysterious" },
{ "data":"bosswords", "word":"fanciful", "distractors":"monstrous,immaculate,disorderly" },
{ "data":"bosswords", "word":"haunted", "distractors":"adorable,elegant,snazzy" },
{ "data":"bosswords", "word":"ominous", "distractors":"colossal,delightful,ridiculous" },
{ "data":"bosswords", "word":"sinister", "distractors":"joyous,gleaming,exquisite" },
{ "data":"bosswords", "word":"serene", "distractors":"scrumptious,supernatural,deceiving" },
{ "data":"bosswords", "word":"tranquil", "distractors":"mysterious,monstrous,immaculate" },
{ "data":"bosswords", "word":"peaceful", "distractors":"ridiculous,eerie,gloomy" },
{ "data":"bosswords", "word":"mystical", "distractors":"scrumptious,disorderly,harsh" },
{ "data":"bosswords", "word":"magical", "distractors":"ominous,serene,forbidding" },
{ "data":"bosswords", "word":"enchanted", "distractors":"sinister,peaceful,dreary" },
{ "data":"bosswords", "word":"gloomy", "distractors":"magnificent,shimmering,blissful" },
{ "data":"bosswords", "word":"forbidding", "distractors":"embellished,captivating,brilliant" },
{ "data":"bosswords", "word":"dreary", "distractors":"enchanting,enthralling,stupendous" },

{ "data":"sound", "id":"101", "name":"cc_howdareyou",                                    "file":"audio/pp_game_countcloudy_howdareyou.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"102", "name":"cc_laugh",                                         "file":"audio/pp_game_countcloudy_laugh.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"108", "name":"lp_beforeyoucontinue",                             "file":"audio/pp_game_luteplayer_beforeyoucontinue.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"109", "name":"lp_bb_clickonthefirstfluffywillow",                "file":"audio/pp_game_luteplayer_bossbattle_clickonfirstfluffywillow.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"110", "name":"lp_bb_finallocation",                              "file":"audio/pp_game_luteplayer_bossbattle_finallocation.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"111", "name":"lp_bb_firstlocation",                              "file":"audio/pp_game_luteplayer_bossbattle_firstlocation.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"112", "name":"lp_bb_goodjob",                                    "file":"audio/pp_game_luteplayer_bossbattle_goodjob.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"113", "name":"lp_bb_nicework",                                   "file":"audio/pp_game_luteplayer_bossbattle_nicework.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"114", "name":"lp_bb_secondfluffywillow",                         "file":"audio/pp_game_luteplayer_bossbattle_secondfluffywillow.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"115", "name":"lp_bb_secondlocation",                             "file":"audio/pp_game_luteplayer_bossbattle_secondlocation.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"116", "name":"lp_bb_thirdfluffywillow",                          "file":"audio/pp_game_luteplayer_bossbattle_thirdfluffywillow.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"117", "name":"lp_bb_tryagain",                                   "file":"audio/pp_game_luteplayer_bossbattle_tryagain.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"118", "name":"lp_bb_tryagain2",                                  "file":"audio/pp_game_luteplayer_bossbattle_tryagain2.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"122", "name":"lp_clickonallofthethingsyoudfindina",              "file":"audio/pp_game_luteplayer_clickonallofthethingsyoudfindina.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"123", "name":"lp_congratsyoumadeitthroughthe",                   "file":"audio/pp_game_luteplayer_congrats_youmadeittrhoughthe.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"124", "name":"lp_doyouwanttogothroughthe",                       "file":"audio/pp_game_luteplayer_doyouwanttogothroughthe.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"125", "name":"lp_bbend_beckysparklingheroine",                   "file":"audio/pp_game_luteplayer_endbossbattle_beckysparklingheroine.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"126", "name":"lp_bbend_beckyyoudidit",                           "file":"audio/pp_game_luteplayer_endbossbattle_beckyyoudidit.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"127", "name":"lp_bbend_beckyyoudiditendofrainbowforcountcloudy", "file":"audio/pp_game_luteplayer_endbossbattle_beckyyoudidit_endofrainbowforcountcloudy.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"128", "name":"lp_bbend_downwithcountcloudy",                     "file":"audio/pp_game_luteplayer_endbossbattle_downwithcountcloudy.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"129", "name":"lp_bbend_sparklingaccomplishment",                 "file":"audio/pp_game_luteplayer_endbossbattle_sparklingaccomplishment.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"130", "name":"lp_bbend_tjaccomplishedtask",                      "file":"audio/pp_game_luteplayer_endbossbattle_tjaccomplishedtask.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"131", "name":"lp_bbend_tjcompletedtask",                         "file":"audio/pp_game_luteplayer_endbossbattle_tjcompletedtask.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"132", "name":"lp_bbend_tjyoucompletedyourrescuemission",         "file":"audio/pp_game_luteplayer_endbossbattle_tjyoucompletedyourrescuemission.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"133", "name":"lp_bbend_violetyouaresobrave",                     "file":"audio/pp_game_luteplayer_endbossbattle_violetyouaresobrave.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"134", "name":"lp_bbend_violetyoudidit",                          "file":"audio/pp_game_luteplayer_endbossbattle_violetyoudidit.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"135", "name":"lp_bbend_violetyoudidithooray",                    "file":"audio/pp_game_luteplayer_endbossbattle_violetyoudidit_hooray.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"136", "name":"lp_excellentyoumaynowchoose",                      "file":"audio/pp_game_luteplayer_excellentyoumaynowchoose.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"138", "name":"lp_gothroughtheforest",                            "file":"audio/pp_game_luteplayer_gothroughtheforest.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"139", "name":"lp_gothroughthevillage",                           "file":"audio/pp_game_luteplayer_gothroughthevillage.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"142", "name":"lp_instructions",                                  "file":"audio/pp_game_luteplayer_instructions.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"146", "name":"lp_journeythroughthecastle",                       "file":"audio/pp_game_luteplayer_journeythroughthecastle.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"147", "name":"lp_journeythroughthefield",                        "file":"audio/pp_game_luteplayer_journeythroughthefield.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"148", "name":"lp_keeptrying",                                    "file":"audio/pp_game_luteplayer_keeptrying.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"150", "name":"lp_offyougo",                                      "file":"audio/pp_game_luteplayer_offyougo.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"152", "name":"lp_onelasttasktodefeatcountcloudy",                "file":"audio/pp_game_luteplayer_onelasttasktodefeatcountcloudy.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"153", "name":"lp_oops",                                          "file":"audio/pp_game_luteplayer_oops.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"154", "name":"lp_oopsyouneedallfivefluffywillows",               "file":"audio/pp_game_luteplayer_oopsyouneedallfivefluffywillows.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"155", "name":"lp_orthe",                                         "file":"audio/pp_game_luteplayer_orthe.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"171", "name":"lp_sorryyouneedtogoback",                          "file":"audio/pp_game_luteplayer_sorryyouneedtogoback.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"172", "name":"lp_travelthroughtheswamp",                         "file":"audio/pp_game_luteplayer_travelthroughtheswamp.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"175", "name":"lp_youhaveselected_drearyswamp",                   "file":"audio/pp_game_luteplayer_youhaveselected_drearyswamp.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"176", "name":"lp_youhaveselected_effervescentvillage",           "file":"audio/pp_game_luteplayer_youhaveselected_efferevescentvillage.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"177", "name":"lp_youhaveselected_enchantedcastle",               "file":"audio/pp_game_luteplayer_youhaveselected_enchantedcastle.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"178", "name":"lp_youhaveselected_fancifulvillage",               "file":"audio/pp_game_luteplayer_youhaveselected_fancifulvillage.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"137", "name":"lp_youhaveselected_forbiddingswamp",               "file":"audio/pp_game_luteplayer_youhaveselected_forbiddingswamp.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"179", "name":"lp_youhaveselected_gloomyswamp",                   "file":"audio/pp_game_luteplayer_youhaveselected_gloomyswamp.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"180", "name":"lp_youhaveselected_hauntedforest",                 "file":"audio/pp_game_luteplayer_youhaveselected_hauntedforest.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"181", "name":"lp_youhaveselected_magicalcastle",                 "file":"audio/pp_game_luteplayer_youhaveselected_magicalcastle.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"182", "name":"lp_youhaveselected_mysticalcastle",                "file":"audio/pp_game_luteplayer_youhaveselected_mysticalcastle.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"151", "name":"lp_youhaveselected_ominousforest",                 "file":"audio/pp_game_luteplayer_youhaveselected_ominousforest.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"183", "name":"lp_youhaveselected_peacefulflowerfield",           "file":"audio/pp_game_luteplayer_youhaveselected_peacefulfield.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"184", "name":"lp_youhaveselected_sereneflowerfield",             "file":"audio/pp_game_luteplayer_youhaveselected_serenefield.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"185", "name":"lp_youhaveselected_sinisterforest",                "file":"audio/pp_game_luteplayer_youhaveselected_sinisterforest.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"186", "name":"lp_youhaveselected_tranquilflowerfield",           "file":"audio/pp_game_luteplayer_youhaveselected_tranquilfield.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"187", "name":"lp_youhaveselected_whimsicalvillage",              "file":"audio/pp_game_luteplayer_youhaveselected_whimsicalvillage.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"188", "name":"lp_youmissed1fluffywillow",                        "file":"audio/pp_game_luteplayer_youmissed1fluffywillow.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"189", "name":"lp_youmissed2fluffywillows",                       "file":"audio/pp_game_luteplayer_youmissed2fluffywillows.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"190", "name":"lp_youmissed3fluffywillows",                       "file":"audio/pp_game_luteplayer_youmissed3fluffywillows.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"191", "name":"lp_youmissed4fluffywillows",                       "file":"audio/pp_game_luteplayer_youmissed4fluffywillows.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"192", "name":"lp_youmissed5fluffywillows",                       "file":"audio/pp_game_luteplayer_youmissed5fluffywillows.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"193", "name":"lp_youmissedafew",                                 "file":"audio/pp_game_luteplayer_youmissedafew.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"194", "name":"pp_becky",                                         "file":"audio/pp_game_prettyprincess_becky.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"195", "name":"pp_chooseahero",                                   "file":"audio/pp_game_prettyprincess_chooseahero.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"197", "name":"pp_chooseyourrescuemission",                       "file":"audio/pp_game_prettyprincess_chooseyourrescuemission.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"198", "name":"pp_congratulations",                               "file":"audio/pp_game_prettyprincess_congratulations.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"199", "name":"pp_countcloudysgloomytower",                       "file":"audio/pp_game_prettyprincess_countcloudysgloomytower.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"202", "name":"pp_hooray",                                        "file":"audio/pp_game_prettyprincess_hooray.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"203", "name":"pp_hoorayyousavedme",                              "file":"audio/pp_game_prettyprincess_hooray_yousavedme.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"205", "name":"pp_instructions",                                  "file":"audio/pp_game_prettyprincess_instructions.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"209", "name":"pp_play",                                          "file":"audio/pp_game_prettyprincess_play.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"211", "name":"pp_sparklepower",                                  "file":"audio/pp_game_prettyprincess_sparklepower.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"212", "name":"pp_thanksforsavingme",                             "file":"audio/pp_game_prettyprincess_thanksforsavingme.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"213", "name":"pp_thedarkstormcloud",                             "file":"audio/pp_game_prettyprincess_thedarkstormcloud.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"214", "name":"pp_theicecoldfrozenlake",                          "file":"audio/pp_game_prettyprincess_theicecoldfrozenlake.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"215", "name":"pp_title",                                         "file":"audio/pp_game_prettyprincess_title.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"216", "name":"pp_tj",                                            "file":"audio/pp_game_prettyprincess_tj.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"217", "name":"pp_violet",                                        "file":"audio/pp_game_prettyprincess_violet.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"218", "name":"pp_yourescuedmefromthatevilcountcloudy",           "file":"audio/pp_game_prettyprincess_yourescuedmefromthatevilcountcloudy.mp3", "lod":"yes", "looping":"no" },

{ "data":"sound", "id":"219", "name":"lp_effervescentvillage",                    "file":"audio/pp_game_luteplayer_effervescentvillage.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"220", "name":"lp_fancifulvillage",                        "file":"audio/pp_game_luteplayer_fancifulvillage.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"221", "name":"lp_whimsicalvillage",                       "file":"audio/pp_game_luteplayer_whimsicalvillage.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"222", "name":"lp_drearyswamp",                            "file":"audio/pp_game_luteplayer_drearyswamp.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"224", "name":"lp_forbiddingswamp",                        "file":"audio/pp_game_luteplayer_forbiddingswamp.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"225", "name":"lp_gloomyswamp",                            "file":"audio/pp_game_luteplayer_gloomyswamp.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"223", "name":"lp_enchantedcastle",                        "file":"audio/pp_game_luteplayer_enchantedcastle.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"227", "name":"lp_magicalcastle",                          "file":"audio/pp_game_luteplayer_magicalcastle.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"228", "name":"lp_mysticalcastle",                         "file":"audio/pp_game_luteplayer_mysticalcastle.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"226", "name":"lp_hauntedforest",                          "file":"audio/pp_game_luteplayer_hauntedforest.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"229", "name":"lp_ominousforest",                          "file":"audio/pp_game_luteplayer_ominousforest.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"232", "name":"lp_sinisterforest",                         "file":"audio/pp_game_luteplayer_sinisterforest.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"230", "name":"lp_peacefulflowerfield",                    "file":"audio/pp_game_luteplayer_peacefulfield.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"231", "name":"lp_sereneflowerfield",                      "file":"audio/pp_game_luteplayer_serenefield.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"233", "name":"lp_tranquilflowerfield",                    "file":"audio/pp_game_luteplayer_tranquilfield.mp3", "lod":"no", "looping":"no" },

{ "data":"sound", "id":"234", "name":"lp_congratulations",                        "file":"audio/pp_game_luteplayer_congratulations.mp3", "lod":"no", "looping":"no" },

{ "data":"sound", "id":"240", "name":"lp_music_village",                          "file":"audio/pp_game_music_village.mp3", "lod":"yes", "looping":"yes" },
{ "data":"sound", "id":"241", "name":"lp_music_forest",                           "file":"audio/pp_game_music_forest.mp3", "lod":"yes", "looping":"yes" },
{ "data":"sound", "id":"242", "name":"lp_music_swamp",                            "file":"audio/pp_game_music_swamp.mp3", "lod":"yes", "looping":"yes" },
{ "data":"sound", "id":"243", "name":"lp_music_magic",                            "file":"audio/pp_game_music_magic.mp3", "lod":"yes", "looping":"yes" },

{ "data":"sound", "id":"260", "name":"pp_theluteplayerwillguideyou",              "file":"audio/pp_game_prettyprincess_theluteplayerwillguideyou.mp3", "lod":"no", "looping":"no" },

{ "data":"sound", "id":"301", "name":"pp_sfx_bounceback",                         "file":"audio/pp_sfx_bounceback.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"302", "name":"pp_sfx_cc_explode1",                        "file":"audio/pp_sfx_cc_explode1.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"303", "name":"pp_sfx_cc_explode2",                        "file":"audio/pp_sfx_cc_explode2.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"304", "name":"pp_sfx_click",                              "file":"audio/pp_sfx_click.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"305", "name":"pp_sfx_endlevel",                           "file":"audio/pp_sfx_endlevel.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"306", "name":"pp_sfx_fw_chimes1",                         "file":"audio/pp_sfx_fw_chimes1.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"307", "name":"pp_sfx_fw_chimes2",                         "file":"audio/pp_sfx_fw_chimes2.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"308", "name":"pp_sfx_fw_chimes3",                         "file":"audio/pp_sfx_fw_chimes3.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"309", "name":"pp_sfx_thunder1",                           "file":"audio/pp_sfx_thunder1.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"310", "name":"pp_sfx_thunder2",                           "file":"audio/pp_sfx_thunder2.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"311", "name":"pp_sfx_thunder3",                           "file":"audio/pp_sfx_thunder3.mp3", "lod":"yes", "looping":"no" },
{ "data":"sound", "id":"312", "name":"pp_sfx_jump",                               "file":"audio/pp_sfx_jump.mp3", "lod":"no", "looping":"no" },
{ "data":"sound", "id":"313", "name":"pp_sfx_landing",                            "file":"audio/pp_sfx_landing.mp3", "lod":"no", "looping":"no" },


{ "data":"end" }

]
